name = "pang"
main = "src/worker.js"
compatibility_date = "2024-10-01"
workers_dev = true

[durable_objects]
bindings = [
  { name = "SEARCH_DO", class_name = "SearchShield" }
]

# 注意：用 new_sqlite_classes（免费计划要求）
[[migrations]]
tag = "v1-sqlite"
new_sqlite_classes = ["SearchShield"]

# KV 绑定
[[kv_namespaces]]
binding = "SEARCH_KV"
id = "671b7951a19848479f0b1c401972ba64"

